using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public class Loading : MonoBehaviour
{

    private AsyncOperation m_operation; 
    private void OnEnable ()
    {
        StartCoroutine(Delay());
    }

    private IEnumerator Delay ()
    {
        yield return new WaitForEndOfFrame();
        m_operation = SceneManager.LoadSceneAsync(AppScenes.GAME_SCENE, LoadSceneMode.Single);
        m_operation.allowSceneActivation = false;

        while (!(m_operation.progress >= 0.9f))
        {
            Debug.Log(m_operation.progress.ToString("0.0000"));
            yield return null;
        }
        
        FinishLoading();

    }

    private void FinishLoading()
    {
        m_operation.allowSceneActivation = true;
    }
}
